version: "3.9"

services:
  django:
    build: .
    container_name: uiverse
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8080 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8080"
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443" # enable for SSL
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - django   # এই নাম Django সার্ভিসের সাথে মিলবে
    restart: always

volumes:
  static_volume:
  media_volume:
